language: node_js
node_js:
  - "stable"
  - "8"
  - "6"
cache:
  directories:
  - node_modules
install:
  - npm install -g codecov
script:
  - npm test -- --coverage
  - codecov
  - npm run build
env:
  global:
    - NODE_ENV=production
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
